### ISSUE TITLE
Проверить работу очередей 

### ISSUE THREAD

**Issue by rtmy** [SGmuwa/Schedule-MIREA-in-calendar#6]
Запускаю ru.mirea.xlsical.Server.Main.main:

```
package ru.mirea.xlsical;

import ru.mirea.xlsical.Server.TaskExecutor;
import ru.mirea.xlsical.interpreter.PackageToServer;

import java.util.ArrayDeque;
import java.util.Queue;
import java.util.concurrent.LinkedBlockingQueue;

public class Main {
    public static int threadNumber = 10;

    public static void main(String[] args) throws Exception
    {
        TaskExecutor taskExecutor = new TaskExecutor();
        Thread[] threadExecutorArr = new Thread[threadNumber];
        for (int i=0; i<threadNumber;++i)
            threadExecutorArr[i] = new Thread(taskExecutor);

        for (int i=0; i<threadNumber;++i)
            threadExecutorArr[i].start();


        String[] s = new String[5];
        taskExecutor.pull(new PackageToServer(null, s, null));
    }
}
```
Получаю ошибку:
```
Exception in thread "main" java.lang.IllegalStateException: Queue full
	at java.util.AbstractQueue.add(AbstractQueue.java:98)
	at ru.mirea.xlsical.Server.TaskExecutor.pull(TaskExecutor.java:80)
	at ru.mirea.xlsical.Main.main(Main.java:25)
```

Необходимо выяснить, почему не работает и исправить.

**Comment by SGmuwa** [comment]
Ошибка `java.lang.illegalstateexception: Queue full` исправлена. Было написано тестирование: https://github.com/SGmuwa/Schedule-MIREA-in-the-calendar/commit/457c450128c0cc893d5d8cf013c3487d0fa699b7#diff-3dda6339c99a020527bad74f0436e968
Функции взаимодействия с очередями переименованы на: `add` и `take`.
Была написана документация для открытия через [Ctrl+Q (Windows) ^J (Mac)](https://resources.jetbrains.com/storage/products/intellij-idea/docs/IntelliJIDEA_ReferenceCard.pdf).
Не исключено возникновения других ошибок TaskExecutor, которые необходимо проверить @markorolek.
